mkdir "Salad Fingers [Converted]" 

youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=M3iOROuTuMA  
ffmpeg -i "Salad Fingers 1 - Spoons-M3iOROuTuMA.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Salad Fingers" -metadata media_type="tv" -metadata season_number="1" -metadata episode_id="1" -metadata artist="David Firth" -metadata title="Spoons" -metadata track="1/11" -metadata genre="Horror" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Salad Fingers - Spoons.mp4"  
move "Salad Fingers - Spoons.mp4" "E:\Users\ordin\Music\Videos\YouTube\David Firth\Salad Fingers [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=cuCw5k-Lph0  
ffmpeg -i "Salad Fingers 2 - Friends-cuCw5k-Lph0.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Salad Fingers" -metadata media_type="tv" -metadata season_number="1" -metadata episode_id="2" -metadata artist="David Firth" -metadata title="Friends" -metadata track="2/11" -metadata genre="Horror" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Salad Fingers - Friends.mp4"  
move "Salad Fingers - Friends.mp4" "E:\Users\ordin\Music\Videos\YouTube\David Firth\Salad Fingers [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=ojoICRzSCOo  
ffmpeg -i "Salad Fingers 3 - Nettles-ojoICRzSCOo.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Salad Fingers" -metadata media_type="tv" -metadata season_number="1" -metadata episode_id="3" -metadata artist="David Firth" -metadata title="Nettles" -metadata track="3/11" -metadata genre="Horror" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Salad Fingers - Nettles.mp4"  
move "Salad Fingers - Nettles.mp4" "E:\Users\ordin\Music\Videos\YouTube\David Firth\Salad Fingers [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=tBNrtrntkJ4  
ffmpeg -i "Salad Fingers 4 - Cage-tBNrtrntkJ4.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Salad Fingers" -metadata media_type="tv" -metadata season_number="1" -metadata episode_id="4" -metadata artist="David Firth" -metadata title="Cage" -metadata track="4/11" -metadata genre="Horror" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Salad Fingers - Cage.mp4"  
move "Salad Fingers - Cage.mp4" "E:\Users\ordin\Music\Videos\YouTube\David Firth\Salad Fingers [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=P_zbGGNI7lo  
ffmpeg -i "Salad Fingers 5 - Picnic-P_zbGGNI7lo.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Salad Fingers" -metadata media_type="tv" -metadata season_number="1" -metadata episode_id="5" -metadata artist="David Firth" -metadata title="Picnic" -metadata track="5/11" -metadata genre="Horror" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Salad Fingers - Picnic.mp4"  
move "Salad Fingers - Picnic.mp4" "E:\Users\ordin\Music\Videos\YouTube\David Firth\Salad Fingers [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=rU2D0ncBFm0  
ffmpeg -i "Salad Fingers 6 - Present-rU2D0ncBFm0.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Salad Fingers" -metadata media_type="tv" -metadata season_number="1" -metadata episode_id="6" -metadata artist="David Firth" -metadata title="Present" -metadata track="6/11" -metadata genre="Horror" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Salad Fingers - Present.mp4"  
move "Salad Fingers - Present.mp4" "E:\Users\ordin\Music\Videos\YouTube\David Firth\Salad Fingers [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=kQNRkdHeK1A  
ffmpeg -i "Salad Fingers 7 - Shore Leave-kQNRkdHeK1A.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Salad Fingers" -metadata media_type="tv" -metadata season_number="1" -metadata episode_id="7" -metadata artist="David Firth" -metadata title="Shore Leave" -metadata track="7/11" -metadata genre="Horror" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Salad Fingers - Shore Leave.mp4"  
move "Salad Fingers - Shore Leave.mp4" "E:\Users\ordin\Music\Videos\YouTube\David Firth\Salad Fingers [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=oykmawhKWhc  
ffmpeg -i "Salad Fingers 8 - Cupboard-oykmawhKWhc.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Salad Fingers" -metadata media_type="tv" -metadata season_number="1" -metadata episode_id="8" -metadata artist="David Firth" -metadata title="Cupboard" -metadata track="8/11" -metadata genre="Horror" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Salad Fingers - Cupboard.mp4"  
move "Salad Fingers - Cupboard.mp4" "E:\Users\ordin\Music\Videos\YouTube\David Firth\Salad Fingers [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=MSOnIS84x1k  
ffmpeg -i "Salad Fingers 9 - Letter-MSOnIS84x1k.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Salad Fingers" -metadata media_type="tv" -metadata season_number="1" -metadata episode_id="9" -metadata artist="David Firth" -metadata title="Letter" -metadata track="9/11" -metadata genre="Horror" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Salad Fingers - Letter.mp4"  
move "Salad Fingers - Letter.mp4" "E:\Users\ordin\Music\Videos\YouTube\David Firth\Salad Fingers [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=1kCVtPhFQNU  
ffmpeg -i "Salad Fingers 10 - Birthday-1kCVtPhFQNU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Salad Fingers" -metadata media_type="tv" -metadata season_number="1" -metadata episode_id="10" -metadata artist="David Firth" -metadata title="Birthday" -metadata track="10/11" -metadata genre="Horror" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Salad Fingers - Birthday.mp4"  
move "Salad Fingers - Birthday.mp4" "E:\Users\ordin\Music\Videos\YouTube\David Firth\Salad Fingers [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=qeE-J-GjAyQ  
ffmpeg -i "Salad Fingers 11 - Glass Brother-qeE-J-GjAyQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Salad Fingers" -metadata media_type="tv" -metadata season_number="1" -metadata episode_id="11" -metadata artist="David Firth" -metadata title="Glass Brother" -metadata track="11/11" -metadata genre="Horror" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Salad Fingers - Glass Brother.mp4"  
move "Salad Fingers - Glass Brother.mp4" "E:\Users\ordin\Music\Videos\YouTube\David Firth\Salad Fingers [Converted]" 

pause 
