youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=9C_HReR_McQ
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=vtkGtXtDlQA
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=sXOdn6vLCuU
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=G9FGgwCQ22w
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=tS_Xq7gSCBM
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=dbL-NSkXnl8

ffmpeg -i "Don't Hug me I'm Scared-9C_HReR_McQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata artist="Don't Hug Me I'm Scared" -metadata show="Don't Hug Me I'm Scared" -metadata media_type="tv" -metadata season_number="01" -metadata episode_id="01" -metadata title="(Episode 1)" -metadata track="1/6" -metadata genre="Horror" -metadata language="English" -metadata encoder="FFmpeg (aac+libx264)" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Don't Hug Me I'm Scared (S01E01).mp4"
ffmpeg -i "Don't Hug Me I'm Scared 2 - TIME-vtkGtXtDlQA.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Don't Hug Me I'm Scared" -metadata media_type="tv" -metadata season_number="01" -metadata episode_id="02" -metadata title="(Episode 2)" -metadata track="2/6" -metadata genre="Horror" -metadata language="English" -metadata encoder="FFmpeg (aac+libx264)" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Don't Hug Me I'm Scared (S01E02).mp4"
ffmpeg -i "Don't Hug Me I'm Scared 3-sXOdn6vLCuU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Don't Hug Me I'm Scared" -metadata media_type="tv" -metadata season_number="01" -metadata episode_id="03" -metadata title="(Episode 3)" -metadata track="3/6" -metadata genre="Horror" -metadata language="English" -metadata encoder="FFmpeg (aac+libx264)" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Don't Hug Me I'm Scared (S01E03).mp4"
ffmpeg -i "Don't Hug Me I'm Scared 4-G9FGgwCQ22w.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Don't Hug Me I'm Scared" -metadata media_type="tv" -metadata season_number="01" -metadata episode_id="04" -metadata title="(Episode 4)" -metadata track="4/6" -metadata genre="Horror" -metadata language="English" -metadata encoder="FFmpeg (aac+libx264)" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Don't Hug Me I'm Scared (S01E04).mp4"
ffmpeg -i "Don't Hug Me I'm Scared 5-tS_Xq7gSCBM.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Don't Hug Me I'm Scared" -metadata media_type="tv" -metadata season_number="01" -metadata episode_id="05" -metadata title="(Episode 5)" -metadata track="5/6" -metadata genre="Horror" -metadata language="English" -metadata encoder="FFmpeg (aac+libx264)" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Don't Hug Me I'm Scared (S01E05).mp4"
ffmpeg -i "Don't Hug Me I'm Scared 6-dbL-NSkXnl8.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Don't Hug Me I'm Scared" -metadata media_type="tv" -metadata season_number="01" -metadata episode_id="06" -metadata title="(Episode 6)" -metadata track="6/6" -metadata genre="Horror" -metadata language="English" -metadata encoder="FFmpeg (aac+libx264)" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Don't Hug Me I'm Scared (S01E06).mp4"

pause
