mkdir "Llamas with Hats [Converted]" 

youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=kZUPCB9533Y  
ffmpeg -i "Llamas with Hats-kZUPCB9533Y.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Llamas with Hats" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="FilmCow" -metadata title="(Episode 1)" -metadata track="1/12" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Llamas with Hats - (Episode 1).mp4"  
move "Llamas with Hats - (Episode 1).mp4" "Llamas with Hats [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=ZpjyH-LkEAg  
ffmpeg -i "Llamas with Hats 2-ZpjyH-LkEAg.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Llamas with Hats" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="FilmCow" -metadata title="(Episode 2)" -metadata track="2/12" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Llamas with Hats - (Episode 2).mp4"  
move "Llamas with Hats - (Episode 2).mp4" "Llamas with Hats [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=49j6_uk0g3k  
ffmpeg -i "Llamas with Hats 3-49j6_uk0g3k.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Llamas with Hats" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="FilmCow" -metadata title="(Episode 3)" -metadata track="3/12" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Llamas with Hats - (Episode 3).mp4"  
move "Llamas with Hats - (Episode 3).mp4" "Llamas with Hats [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=SJixW2u4IvQ  
ffmpeg -i "Llamas with Hats 4-SJixW2u4IvQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Llamas with Hats" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="FilmCow" -metadata title="(Episode 4)" -metadata track="4/12" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Llamas with Hats - (Episode 4).mp4"  
move "Llamas with Hats - (Episode 4).mp4" "Llamas with Hats [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=71iZieJWmmk  
ffmpeg -i "Llamas with Hats 5-71iZieJWmmk.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Llamas with Hats" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="FilmCow" -metadata title="(Episode 5)" -metadata track="5/12" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Llamas with Hats - (Episode 5).mp4"  
move "Llamas with Hats - (Episode 5).mp4" "Llamas with Hats [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=kVzaBq4ycWg  
ffmpeg -i "Llamas with Hats 6-kVzaBq4ycWg.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Llamas with Hats" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="FilmCow" -metadata title="(Episode 6)" -metadata track="6/12" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Llamas with Hats - (Episode 6).mp4"  
move "Llamas with Hats - (Episode 6).mp4" "Llamas with Hats [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=4s9-sJwNz2c  
ffmpeg -i "Llamas with Hats 7-4s9-sJwNz2c.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Llamas with Hats" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="FilmCow" -metadata title="(Episode 7)" -metadata track="7/12" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Llamas with Hats - (Episode 7).mp4"  
move "Llamas with Hats - (Episode 7).mp4" "Llamas with Hats [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=kHDghTE7Llo  
ffmpeg -i "Llamas with Hats 8-kHDghTE7Llo.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Llamas with Hats" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="FilmCow" -metadata title="(Episode 8)" -metadata track="8/12" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Llamas with Hats - (Episode 8).mp4"  
move "Llamas with Hats - (Episode 8).mp4" "Llamas with Hats [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=RYqBDTsHZsQ  
ffmpeg -i "Llamas with Hats 9-RYqBDTsHZsQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Llamas with Hats" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="FilmCow" -metadata title="(Episode 9)" -metadata track="9/12" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Llamas with Hats - (Episode 9).mp4"  
move "Llamas with Hats - (Episode 9).mp4" "Llamas with Hats [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=cyv-gSJvWpU  
ffmpeg -i "Llamas with Hats 10-cyv-gSJvWpU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Llamas with Hats" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="FilmCow" -metadata title="(Episode 10)" -metadata track="10/12" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Llamas with Hats - (Episode 10).mp4"  
move "Llamas with Hats - (Episode 10).mp4" "Llamas with Hats [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=C_-zC2qcx4M  
ffmpeg -i "Llamas with Hats 11-C_-zC2qcx4M.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Llamas with Hats" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="FilmCow" -metadata title="(Episode 11)" -metadata track="11/12" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Llamas with Hats - (Episode 11).mp4"  
move "Llamas with Hats - (Episode 11).mp4" "Llamas with Hats [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=QXI0u3qyFqA  
ffmpeg -i "Llamas with Hats 12-QXI0u3qyFqA.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Llamas with Hats" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="FilmCow" -metadata title="(Episode 12)" -metadata track="12/12" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Llamas with Hats - (Episode 12).mp4"  
move "Llamas with Hats - (Episode 12).mp4" "Llamas with Hats [Converted]" 

pause 
