mkdir "Angry Video Game Nerd [Converted]" 

youtube-dl --embed-subs -f 242+251 https://www.youtube.com/watch?v=V4we8iFk-fY  
ffmpeg -i "Castlevania II - Simon's Quest (NES) - Angry Video Game Nerd (AVGN)-V4we8iFk-fY.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Castlevania II: Simon's Quest" -metadata track="1/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Castlevania II - Simon's Quest.mp4"  
move "Angry Video Game Nerd - Castlevania II - Simon's Quest.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 242+251 https://www.youtube.com/watch?v=6M_4Yqk65f8  
ffmpeg -i "Dr. Jekyll and Mr. Hyde (NES) - Angry Video Game Nerd (AVGN)-6M_4Yqk65f8.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Dr. Jekyll and Mr. Hyde" -metadata track="2/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Dr. Jekyll and Mr. Hyde.mp4"  
move "Angry Video Game Nerd - Dr. Jekyll and Mr. Hyde.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 242+251 https://www.youtube.com/watch?v=9DfdRdOM_B0  
ffmpeg -i "The Karate Kid (NES) - Angry Video Game Nerd (AVGN)-9DfdRdOM_B0.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="The Karate Kid" -metadata track="3/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - The Karate Kid.mp4"  
move "Angry Video Game Nerd - The Karate Kid.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 242+251 https://www.youtube.com/watch?v=l-6WakV0kWM  
ffmpeg -i "Who Framed Roger Rabbit (NES) - Angry Video Game Nerd (AVGN)-l-6WakV0kWM.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Who Framed Roger Rabbit" -metadata track="4/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Who Framed Roger Rabbit.mp4"  
move "Angry Video Game Nerd - Who Framed Roger Rabbit.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 242+251 https://www.youtube.com/watch?v=XjUz8IT0CYg  
ffmpeg -i "Teenage Mutant Ninja Turtles (NES) - Angry Video Game Nerd (AVGN)-XjUz8IT0CYg.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Teenage Mutant Ninja Turtles" -metadata track="5/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Teenage Mutant Ninja Turtles.mp4"  
move "Angry Video Game Nerd - Teenage Mutant Ninja Turtles.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 242+251 https://www.youtube.com/watch?v=y306cWw98a4  
ffmpeg -i "Back to the Future (NES) - Angry Video Game Nerd (AVGN)-y306cWw98a4.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Back to the Future" -metadata track="6/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Back to the Future.mp4"  
move "Angry Video Game Nerd - Back to the Future.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 242+251 https://www.youtube.com/watch?v=qVBerX6Dzmc  
ffmpeg -i "McKids - Angry Video Game Nerd (AVGN)-qVBerX6Dzmc.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="McKids" -metadata track="7/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - McKids.mp4"  
move "Angry Video Game Nerd - McKids.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 242+251 https://www.youtube.com/watch?v=QVS0Uks4ZUw  
ffmpeg -i "Wally Bear and the No! Gang - Angry Video Game Nerd (AVGN)-QVS0Uks4ZUw.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Wally Bear and the No! Gang" -metadata track="8/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Wally Bear and the No Gang.mp4"  
move "Angry Video Game Nerd - Wally Bear and the No Gang.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=sayp5lieKuU  
ffmpeg -i "Master Chu and the Drunkard Hu - Angry Video Game Nerd (AVGN)-sayp5lieKuU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Master Chu and the Drunkard Hu" -metadata track="9/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Master Chu and the Drunkard Hu.mp4"  
move "Angry Video Game Nerd - Master Chu and the Drunkard Hu.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 242+251 https://www.youtube.com/watch?v=ofM11nPzFo0  
ffmpeg -i "Top Gun (NES) - Angry Video Game Nerd (AVGN)-ofM11nPzFo0.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Top Gun" -metadata track="10/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Top Gun.mp4"  
move "Angry Video Game Nerd - Top Gun.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=kMg6_IXCjo4  
ffmpeg -i "Double Dragon III (NES) - Angry Video Game Nerd (AVGN)-kMg6_IXCjo4.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Double Dragon III" -metadata track="11/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Double Dragon III.mp4"  
move "Angry Video Game Nerd - Double Dragon III.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=1raUvGNbZFg  
ffmpeg -i "Friday the 13th (NES) - Angry Video Game Nerd (AVGN)-1raUvGNbZFg.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Friday the 13th" -metadata track="12/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Friday the 13th.mp4"  
move "Angry Video Game Nerd - Friday the 13th.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=3p713bNaO4A  
ffmpeg -i "A Nightmare On Elm Street (NES) - Angry Video Game Nerd (AVGN)-3p713bNaO4A.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="A Nightmare on Elm Street" -metadata track="13/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - A Nightmare on Elm Street.mp4"  
move "Angry Video Game Nerd - A Nightmare on Elm Street.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=MYDuy7wM8Gk  
ffmpeg -i "The Power Glove (NES) - Angry Video Game Nerd (AVGN)-MYDuy7wM8Gk.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="The Power Glove" -metadata track="14/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - The Power Glove.mp4"  
move "Angry Video Game Nerd - The Power Glove.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=OEVzPCY2T-g  
ffmpeg -i "Chronologically Confused about Sequel Titles - Angry Video Game Nerd (AVGN)-OEVzPCY2T-g.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Chronologically Confused About Sequel Titles" -metadata track="15/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Chronologically Confused About Sequel Titles.mp4"  
move "Angry Video Game Nerd - Chronologically Confused About Sequel Titles.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=v7poR6G3hec  
ffmpeg -i "Rocky (SMS) - Angry Video Game Nerd (AVGN)-v7poR6G3hec.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Rocky" -metadata track="16/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Rocky.mp4"  
move "Angry Video Game Nerd - Rocky.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=LkNvQYiM6bw  
ffmpeg -i "Bible Games - Angry Video Game Nerd (AVGN)-LkNvQYiM6bw.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Bible Games" -metadata track="17/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Bible Games.mp4"  
move "Angry Video Game Nerd - Bible Games.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=KoLrymTT2co  
:: Has episode 18 and 19 merged
ffmpeg -i "Teenage Mutant Ninja Turtles III - Angry Video Game Nerd (Re-Edit)-KoLrymTT2co.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Teenage Mutant Ninja Turtles III" -metadata track="18/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Teenage Mutant Ninja Turtles III.mp4"  
move "Angry Video Game Nerd - Teenage Mutant Ninja Turtles III.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=AknyR-kRvLc  
ffmpeg -i "Atari 5200 - Angry Video Game Nerd (AVGN)-AknyR-kRvLc.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Atari 5200" -metadata track="19/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Atari 5200.mp4"  
move "Angry Video Game Nerd - Atari 5200.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=TLVGmvmNitg  
ffmpeg -i "Ghostbusters (NES) - Angry Video Game Nerd (AVGN)-TLVGmvmNitg.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Ghostbusters" -metadata track="20/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Ghostbusters.mp4"  
move "Angry Video Game Nerd - Ghostbusters.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=qF2snKCmqJo  
ffmpeg -i "Ghostbusters Part 2 - Angry Video Game Nerd (AVGN)-qF2snKCmqJo.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Ghostbusters (Part 2)" -metadata track="21/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Ghostbusters (Part 2).mp4"  
move "Angry Video Game Nerd - Ghostbusters (Part 2).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=kZfq-IPlLF8  
ffmpeg -i "Ghostbusters Part 3 - Angry Video Game Nerd (AVGN)-kZfq-IPlLF8.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Ghostbusters (Part 3)" -metadata track="22/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Ghostbusters (Part 3).mp4"  
move "Angry Video Game Nerd - Ghostbusters (Part 3).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=omW1E7rv7IM  
ffmpeg -i "Spider-Man - Angry Video Game Nerd (AVGN)-omW1E7rv7IM.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Spider-Man" -metadata track="23/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Spider-Man.mp4"  
move "Angry Video Game Nerd - Spider-Man.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=g2eH3vYbdGo  
ffmpeg -i "Sega CD - Angry Video Game Nerd (AVGN)-g2eH3vYbdGo.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Sega CD" -metadata track="24/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Sega CD.mp4"  
move "Angry Video Game Nerd - Sega CD.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=VvR_3OTxs8A  
ffmpeg -i "Sega 32X - Angry Video Game Nerd (AVGN)-VvR_3OTxs8A.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Sega 32X" -metadata track="25/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Sega 32X.mp4"  
move "Angry Video Game Nerd - Sega 32X.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=gvnRBywkUZ0  
ffmpeg -i "Silver Surfer (NES) - Angry Video Game Nerd (AVGN)-gvnRBywkUZ0.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Silver Surfer" -metadata track="26/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Silver Surfer.mp4"  
move "Angry Video Game Nerd - Silver Surfer.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=RL0YWB8wMDs  
ffmpeg -i "Die Hard - Angry Video Game Nerd (AVGN)-RL0YWB8wMDs.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Die Hard" -metadata track="27/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Die Hard.mp4"  
move "Angry Video Game Nerd - Die Hard.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=t475kPIEXPg  
ffmpeg -i "Independence Day (PS1) - Angry Video Game Nerd (AVGN)-t475kPIEXPg.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Independence Day" -metadata track="28/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Independence Day.mp4"  
move "Angry Video Game Nerd - Independence Day.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=mKnl0CvfeLs  
ffmpeg -i "The Simpsons - Angry Video Game Nerd (AVGN)-mKnl0CvfeLs.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="The Simpsons" -metadata track="29/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - The Simpsons.mp4"  
move "Angry Video Game Nerd - The Simpsons.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=M1tU61Nyv1w  
ffmpeg -i "Bugs Bunny Birthday Blowout (NES) - Angry Video Game Nerd (AVGN)-M1tU61Nyv1w.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Bugs Bunny Birthday Blowout" -metadata track="30/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Bugs Bunny Birthday Blowout.mp4"  
move "Angry Video Game Nerd - Bugs Bunny Birthday Blowout.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=7E5GtYj7fUE  
ffmpeg -i "AVGN - ATARI PORNO-7E5GtYj7fUE.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Atari Porn" -metadata track="31/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Atari Porn.mp4"  
move "Angry Video Game Nerd - Atari Porn.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=eegQI9WM6mk  
ffmpeg -i "Nintendo Power - Angry Video Game Nerd (AVGN)-eegQI9WM6mk.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Nintendo Power" -metadata track="32/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Nintendo Power.mp4"  
move "Angry Video Game Nerd - Nintendo Power.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=B0iwC58K6t0  
ffmpeg -i "Fester's Quest (NES)  - Angry Video Game Nerd (AVGN)-B0iwC58K6t0.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Fester's Quest" -metadata track="33/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Fester's Quest.mp4"  
move "Angry Video Game Nerd - Fester's Quest.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=bVtwVXMPBY8  
ffmpeg -i "Texas Chainsaw Massacre (Atari 2600) - Angry Video Game Nerd (AVGN)-bVtwVXMPBY8.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Texas Chainsaw Massacre" -metadata track="34/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Texas Chainsaw Massacre.mp4"  
move "Angry Video Game Nerd - Texas Chainsaw Massacre.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=a0G_8gHDsL8  
ffmpeg -i "Halloween (Atari 2600) - Angry Video Game Nerd (AVGN)-a0G_8gHDsL8.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Halloween" -metadata track="35/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Halloween.mp4"  
move "Angry Video Game Nerd - Halloween.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=00xIvTOLrYA  
ffmpeg -i "Dragon's Lair (NES) - Angry Video Game Nerd (AVGN)-00xIvTOLrYA.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Dragon's Lair" -metadata track="36/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Dragon's Lair.mp4"  
move "Angry Video Game Nerd - Dragon's Lair.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=CyqK8wqwYmc  
ffmpeg -i "Christmas Carol Part 1 - Angry Video Game Nerd (AVGN)-CyqK8wqwYmc.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Christmas Carol (Part 1)" -metadata track="37/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Christmas Carol (Part 1).mp4"  
move "Angry Video Game Nerd - Christmas Carol (Part 1).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=l7XIbwtMl4Y  
ffmpeg -i "Christmas Carol Part 2 - Angry Video Game Nerd (AVGN)-l7XIbwtMl4Y.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Christmas Carol (Part 2)" -metadata track="38/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Christmas Carol (Part 2).mp4"  
move "Angry Video Game Nerd - Christmas Carol (Part 2).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=cHIP9UtkQDQ  
ffmpeg -i "The Legend of Zelda Timeline - Angry Video Game Nerd (AVGN)-cHIP9UtkQDQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="The Legend of Zelda Timeline" -metadata track="39/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - The Legend of Zelda Timeline.mp4"  
move "Angry Video Game Nerd - The Legend of Zelda Timeline.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=ttd_HcgaoXQ  
ffmpeg -i "Rambo - NES - Angry Video Game Nerd (AVGN)-ttd_HcgaoXQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Rambo" -metadata track="40/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Rambo.mp4"  
move "Angry Video Game Nerd - Rambo.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=OyVAp0tOk5A  
ffmpeg -i "Virtual Boy - Angry Video Game Nerd (AVGN)-OyVAp0tOk5A.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Virtual Boy" -metadata track="41/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Virtual Boy.mp4"  
move "Angry Video Game Nerd - Virtual Boy.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=HTLUOgP21UY  
ffmpeg -i "The Wizard Of Oz (Super Nintendo) - Angry Video Game Nerd (AVGN)-HTLUOgP21UY.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="The Wizard of Oz" -metadata track="42/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - The Wizard of Oz.mp4"  
move "Angry Video Game Nerd - The Wizard of Oz.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=4yn52NTdV0c  
ffmpeg -i "Doublevision (Part 1) Intellivision - Angry Video Game Nerd (AVGN)-4yn52NTdV0c.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Doublevision Intellivision (Part 1)" -metadata track="43/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Doublevision Intellivision (Part 1).mp4"  
move "Angry Video Game Nerd - Doublevision Intellivision (Part 1).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=rBMO8F1I-h4  
ffmpeg -i "Doublevision (Part 2) ColecoVision - Angry Video Game Nerd (AVGN)-rBMO8F1I-h4.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Doublevision ColecoVision (Part 2)" -metadata track="44/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Doublevision ColecoVision (Part 2).mp4"  
move "Angry Video Game Nerd - Doublevision ColecoVision (Part 2).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=YWRzXAtDgN0  
ffmpeg -i "Super Mario Bros. 3 and The Wizard - Angry Video Game Nerd (AVGN)-YWRzXAtDgN0.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Super Mario Bros. 3 and The Wizard - Angry Video Game Nerd (AVGN)-YWRzXAtDgN0.webm" -metadata track="45/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Super Mario Bros. 3 and The Wizard.mp4"  
move "Angry Video Game Nerd - Super Mario Bros. 3 and The Wizard.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=9kBMscW_dVg  
ffmpeg -i "NES Accessories - Angry Video Game Nerd (AVGN)-9kBMscW_dVg.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="NES Accessories" -metadata track="46/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - NES Accessories.mp4"  
move "Angry Video Game Nerd - NES Accessories.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=7O82pX2XQIQ  
ffmpeg -i "Indiana Jones Trilogy - Angry Video Game Nerd (AVGN)-7O82pX2XQIQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Indiana Jones Trilogy" -metadata track="47/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Indiana Jones Trilogy.mp4"  
move "Angry Video Game Nerd - Indiana Jones Trilogy.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=1CNddEz9dak  
ffmpeg -i "Star Trek - Angry Video Game Nerd (AVGN)-1CNddEz9dak.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Star Trek" -metadata track="48/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Star Trek.mp4"  
move "Angry Video Game Nerd - Star Trek.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=9NyWqiHQs7c  
ffmpeg -i "Superman (NES) - Angry Video Game Nerd (AVGN)-9NyWqiHQs7c.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Superman" -metadata track="49/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Superman.mp4"  
move "Angry Video Game Nerd - Superman.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=1dJXgJ1c4vY  
ffmpeg -i "Superman 64 (N64) - Angry Video Game Nerd (AVGN)-1dJXgJ1c4vY.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Superman 64" -metadata track="50/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Superman 64.mp4"  
move "Angry Video Game Nerd - Superman 64.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=JFvtk5toGJg  
ffmpeg -i "Batman Part 1 - Angry Video Game Nerd (AVGN)-JFvtk5toGJg.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Batman (Part 1)" -metadata track="51/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Batman (Part 1).mp4"  
move "Angry Video Game Nerd - Batman (Part 1).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=Dvs6JDSBqoE  
ffmpeg -i "Batman (Part 2) - Angry Video Game Nerd (AVGN)-Dvs6JDSBqoE.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Batman (Part 2)" -metadata track="52/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Batman (Part 2).mp4"  
move "Angry Video Game Nerd - Batman (Part 2).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=cgCSbOy4mNU  
ffmpeg -i "Deadly Towers (NES) - Angry Video Game Nerd (AVGN)-cgCSbOy4mNU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Deadly Towers" -metadata track="53/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Deadly Towers.mp4"  
move "Angry Video Game Nerd - Deadly Towers.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=UD7k4mTThLY  
ffmpeg -i "Battletoads (NES) - Angry Video Game Nerd (AVGN)-UD7k4mTThLY.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Battletoads" -metadata track="54/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Battletoads.mp4"  
move "Angry Video Game Nerd - Battletoads.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=t9nxIUhZCCw  
ffmpeg -i "Dick Tracy (NES) - Angry Video Game Nerd (AVGN)-t9nxIUhZCCw.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Dick Tracy" -metadata track="55/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Dick Tracy.mp4"  
move "Angry Video Game Nerd - Dick Tracy.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=sDR8HKC9wgI  
ffmpeg -i "Dracula - Angry Video Game Nerd (AVGN)-sDR8HKC9wgI.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Dracula" -metadata track="56/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Dracula.mp4"  
move "Angry Video Game Nerd - Dracula.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=cOfHlihgOn0  
ffmpeg -i "Frankenstein - Angry Video Game Nerd (AVGN)-cOfHlihgOn0.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Frankenstein" -metadata track="57/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Frankenstein.mp4"  
move "Angry Video Game Nerd - Frankenstein.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=tl2Wz1qlzco  
ffmpeg -i "Hotel Mario (CD-I Part 1) - Angry Video Game Nerd (AVGN)-tl2Wz1qlzco.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Hotel Mario (CD-I Part 1)" -metadata track="58/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Hotel Mario (CD-I Part 1).mp4"  
move "Angry Video Game Nerd - Hotel Mario (CD-I Part 1).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=xLxqfmpjB-U  
ffmpeg -i "Zelda Wand of Gamelon (CD-I Part 2) - Angry Video Game Nerd (AVGN)-xLxqfmpjB-U.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Zelda Wand of Gamelon (CD-I Part 2)" -metadata track="59/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Zelda Wand of Gamelon (CD-I Part 2).mp4"  
move "Angry Video Game Nerd - Zelda Wand of Gamelon (CD-I Part 2).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=eHcoOLMXono  
ffmpeg -i "Faces of Evil _ Zelda's Adventure (CD-I Part 3) - Angry Video Game Nerd-eHcoOLMXono.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Zelda Faces of Evil and Zelda's Adventure (CD-I Part 3)" -metadata track="60/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Zelda Faces of Evil and Zelda's Adventure (CD-I Part 3).mp4"  
move "Angry Video Game Nerd - Zelda Faces of Evil and Zelda's Adventure (CD-I Part 3).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=_dUVZozf-i0  
ffmpeg -i "Bible Games 2 - Angry Video Game Nerd (AVGN)-_dUVZozf-i0.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Bible Games 2" -metadata track="61/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Bible Games 2.mp4"  
move "Angry Video Game Nerd - Bible Games 2.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=zk1C0AhshtU  
ffmpeg -i "Michael Jackson's Moonwalker (Sega Genesis) - Angry Video Game Nerd (AVGN)-zk1C0AhshtU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Michael Jackson's Moonwalker" -metadata track="62/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Michael Jackson's Moonwalker.mp4"  
move "Angry Video Game Nerd - Michael Jackson's Moonwalker.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=kMz7JkVplpM  
ffmpeg -i "Milon's Secret Castle (NES) - Angry Video Game Nerd (AVGN)-kMz7JkVplpM.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Milon's Secret Castle" -metadata track="63/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Milon's Secret Castle.mp4"  
move "Angry Video Game Nerd - Milon's Secret Castle.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=CGEGon-Qc_Q  
ffmpeg -i "Atari Jaguar (Part 1) - Angry Video Game Nerd (AVGN)-CGEGon-Qc_Q.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Atari Jaguar (Part 1)" -metadata track="64/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Atari Jaguar (Part 1).mp4"  
move "Angry Video Game Nerd - Atari Jaguar (Part 1).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=3LVcvkLCUtU  
ffmpeg -i "Atari Jaguar (Part 2) - Angry Video Game Nerd (AVGN)-3LVcvkLCUtU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Atari Jaguar (Part 2)" -metadata track="65/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Atari Jaguar (Part 2).mp4"  
move "Angry Video Game Nerd - Atari Jaguar (Part 2).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=bHyTzPtEAhk  
ffmpeg -i "Metal Gear (NES) - Angry Video Game Nerd (AVGN)-bHyTzPtEAhk.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Metal Gear" -metadata track="66/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Metal Gear.mp4"  
move "Angry Video Game Nerd - Metal Gear.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=kDAKxjG7VaI  
ffmpeg -i "Odyssey - Angry Video Game Nerd (AVGN)-kDAKxjG7VaI.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Odyssey" -metadata track="67/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Odyssey.mp4"  
move "Angry Video Game Nerd - Odyssey.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=-LKK-6bmDgQ  
ffmpeg -i "X-Men - Angry Video Game Nerd (AVGN)--LKK-6bmDgQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="X-Men" -metadata track="68/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - X-Men.mp4"  
move "Angry Video Game Nerd - X-Men.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=24sBGjAAWEY  
ffmpeg -i "Terminator - Angry Video Game Nerd (AVGN)-24sBGjAAWEY.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Terminator" -metadata track="69/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Terminator.mp4"  
move "Angry Video Game Nerd - Terminator.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=rmq6bCVD4V8  
ffmpeg -i "Terminator (Part 2) - Angry Video Game Nerd (AVGN)-rmq6bCVD4V8.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Terminator (Part 2)" -metadata track="70/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Terminator (Part 2).mp4"  
move "Angry Video Game Nerd - Terminator (Part 2).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=km9vYa2GIUI  
ffmpeg -i "Transformers - Angry Video Game Nerd (AVGN)-km9vYa2GIUI.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Transformers" -metadata track="71/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Transformers.mp4"  
move "Angry Video Game Nerd - Transformers.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=69ybxGPnuag  
ffmpeg -i "Mario is Missing - Angry Video Game Nerd - Episode 73-69ybxGPnuag.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Mario is Missing" -metadata track="72/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Mario is Missing.mp4"  
move "Angry Video Game Nerd - Mario is Missing.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=DyaF_gCKWsI  
ffmpeg -i "Plumbers Don't Wear Ties (Panasonic 3DO) - Angry Video Game Nerd (AVGN)-DyaF_gCKWsI.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Plumbers Don't Wear Ties" -metadata track="73/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Plumbers Don't Wear Ties.mp4"  
move "Angry Video Game Nerd - Plumbers Don't Wear Ties.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=wai9CnvatBo  
ffmpeg -i "Bugs Bunny's Crazy Castle - Angry Video Game Nerd - Episode 75-wai9CnvatBo.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Bugs Bunny's Crazy Castle" -metadata track="74/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Bugs Bunny's Crazy Castle.mp4"  
move "Angry Video Game Nerd - Bugs Bunny's Crazy Castle.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=FJEXpsDB2XQ  
ffmpeg -i "Super Pitfall (NES) - Angry Video Game Nerd (AVGN)-FJEXpsDB2XQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Super Pitfall" -metadata track="75/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Super Pitfall.mp4"  
move "Angry Video Game Nerd - Super Pitfall.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=C8mQHotlaFo  
ffmpeg -i "Godzilla - Angry Video Game Nerd (AVGN)-C8mQHotlaFo.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Godzilla" -metadata track="76/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Godzilla.mp4"  
move "Angry Video Game Nerd - Godzilla.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=2cWGZkK-KsY  
ffmpeg -i "Wayne's World - Angry Video Game Nerd (AVGN)-2cWGZkK-KsY.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Wayne's World" -metadata track="77/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Wayne's World.mp4"  
move "Angry Video Game Nerd - Wayne's World.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=Hfo6hoN0PUw  
ffmpeg -i "Castlevania (Part 1) - Angry Video Game Nerd (AVGN)-Hfo6hoN0PUw.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Castlevania" -metadata track="78/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Castlevania.mp4"  
move "Angry Video Game Nerd - Castlevania.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=UrLdIiW6bEo  
ffmpeg -i "Castlevania (Part 2) - Angry Video Game Nerd (AVGN)-UrLdIiW6bEo.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Castlevania (Part 2)" -metadata track="79/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Castlevania (Part 2).mp4"  
move "Angry Video Game Nerd - Castlevania (Part 2).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=4C0xI41RtaU  
ffmpeg -i "Castlevania (Part 3) - Angry Video Game Nerd (AVGN)-4C0xI41RtaU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Castlevania (Part 3)" -metadata track="80/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Castlevania (Part 3).mp4"  
move "Angry Video Game Nerd - Castlevania (Part 3).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=sSoQWmcr5mc  
ffmpeg -i "Castlevania (Part 4) - Angry Video Game Nerd - (AVGN)-sSoQWmcr5mc.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Castlevania (Part 4)" -metadata track="81/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Castlevania (Part 4).mp4"  
move "Angry Video Game Nerd - Castlevania (Part 4).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=NEwgFmL31RQ  
ffmpeg -i "Little Red Hood (unlicensed NES) - Angry Video Game Nerd (AVGN)-NEwgFmL31RQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Little Red Hood" -metadata track="82/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Little Red Hood.mp4"  
move "Angry Video Game Nerd - Little Red Hood.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=QGrHqz3opgM  
ffmpeg -i "Winter Games - Angry Video Game Nerd-QGrHqz3opgM.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Winter Games" -metadata track="83/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Winter Games.mp4"  
move "Angry Video Game Nerd - Winter Games.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=gU21wBNSVWU  
ffmpeg -i "Street Fighter 2010 (NES) - Angry Video Game Nerd (AVGN)-gU21wBNSVWU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Street Fighter 2010" -metadata track="84/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Street Fighter 2010.mp4"  
move "Angry Video Game Nerd - Street Fighter 2010.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=nFOf70RyERU  
ffmpeg -i "Hydlide (NES) - Angry Video Game Nerd (AVGN)-nFOf70RyERU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Hydlide" -metadata track="85/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Hydlide.mp4"  
move "Angry Video Game Nerd - Hydlide.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=6t2YvyLqw3c  
ffmpeg -i "Ninja Gaiden (NES) - Angry Video Game Nerd (AVGN)-6t2YvyLqw3c.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Ninja Gaiden" -metadata track="86/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Ninja Gaiden.mp4"  
move "Angry Video Game Nerd - Ninja Gaiden.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=LWltQ9UN5vE  
ffmpeg -i "SwordQuest (Atari 2600) - Angry Video Game Nerd (AVGN)-LWltQ9UN5vE.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="SwordQuest" -metadata track="87/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - SwordQuest.mp4"  
move "Angry Video Game Nerd - SwordQuest.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=FvT8jG1OVdI  
ffmpeg -i "Pong Consoles - Angry Video Game Nerd (AVGN)-FvT8jG1OVdI.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Pong Consoles" -metadata track="88/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Pong Consoles.mp4"  
move "Angry Video Game Nerd - Pong Consoles.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=a4QBeADNM34  
ffmpeg -i "Action 52 (NES) - Angry Video Game Nerd (AVGN)-a4QBeADNM34.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Action 52" -metadata track="89/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Action 52.mp4"  
move "Angry Video Game Nerd - Action 52.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=hwmoJkHS-2E  
ffmpeg -i "Cheetahmen (NES) - Angry Video Game Nerd (AVGN)-hwmoJkHS-2E.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Cheetahmen" -metadata track="90/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Cheetahmen.mp4"  
move "Angry Video Game Nerd - Cheetahmen.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=HdWRTleizFU  
ffmpeg -i "Game Glitches - Angry Video Game Nerd (AVGN)-HdWRTleizFU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Game Glitches" -metadata track="91/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Game Glitches.mp4"  
move "Angry Video Game Nerd - Game Glitches.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=sDBfNTf4ORY  
ffmpeg -i "Zelda II - The Adventure of Link (NES) - Angry Video Game Nerd (AVGN)-sDBfNTf4ORY.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Zelda II: The Adventure of Link" -metadata track="92/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Zelda II - The Adventure of Link.mp4"  
move "Angry Video Game Nerd - Zelda II - The Adventure of Link.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=Fz92prJ3XlM  
ffmpeg -i "Back to the Future ReRevisited  - Angry Video Game Nerd (AVGN)-Fz92prJ3XlM.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Back to the Future (ReRevisited)" -metadata track="93/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Back to the Future (ReRevisited).mp4"  
move "Angry Video Game Nerd - Back to the Future (ReRevisited).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=EjXn5qiM8Zw  
ffmpeg -i "Dr. Jekyll and Mr. Hyde Revisited (NES) - Angry Video Game Nerd (AVGN)-EjXn5qiM8Zw.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Dr. Jekyll and Mr. Hyde (Revisited)" -metadata track="94/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Dr. Jekyll and Mr. Hyde (Revisited).mp4"  
move "Angry Video Game Nerd - Dr. Jekyll and Mr. Hyde (Revisited).mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=w2ZX_ToJHFk  
ffmpeg -i "Lester the Unlikely (SNES) - Angry Video Game Nerd (AVGN)-w2ZX_ToJHFk.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Lester the Unlikely" -metadata track="95/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Lester the Unlikely.mp4"  
move "Angry Video Game Nerd - Lester the Unlikely.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=iMINBv_Dqvs  
ffmpeg -i "How the Nerd Stole Christmas - Angry Video Game Nerd (AVGN)-iMINBv_Dqvs.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="How the Nerd Stole Christmas" -metadata track="96/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - How the Nerd Stole Christmas.mp4"  
move "Angry Video Game Nerd - How the Nerd Stole Christmas.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=iSjq4Am-5Aw  
ffmpeg -i "Day Dreamin Davey (NES) - Angry Video Game Nerd (AVGN)-iSjq4Am-5Aw.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Day Dreamin' Davey" -metadata track="97/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Day Dreamin' Davey.mp4"  
move "Angry Video Game Nerd - Day Dreamin' Davey.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=F2bKVEVUOPg  
ffmpeg -i "Star Wars Games  - Angry Video Game Nerd (AVGN)-F2bKVEVUOPg.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Star Wars Games" -metadata track="98/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - Star Wars Games.mp4"  
move "Angry Video Game Nerd - Star Wars Games.mp4" "Angry Video Game Nerd [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=vBjejMlyxLk  
ffmpeg -i "R.O.B. the Robot (NES) - Angry Video Game Nerd (AVGN)-vBjejMlyxLk.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Angry Video Game Nerd" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="R.O.B. the Robot" -metadata track="99/189" -metadata genre="Comedy/Documentary" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Angry Video Game Nerd - R.O.B. the Robot.mp4"  
move "Angry Video Game Nerd - R.O.B. the Robot.mp4" "Angry Video Game Nerd [Converted]" 
