chcp 65001

mkdir "You Know What's BS [Converted]" 

youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=bN6fxqvGBSs  
ffmpeg -i "You Know What’s BS! DVD Packaging-bN6fxqvGBSs.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="DVD Packaging" -metadata track="1/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - DVD Packaging.mp4"  
move "You Know What's BS - DVD Packaging.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=FffTJk-gFKc  
ffmpeg -i "You Know What’s BS! Pennies-FffTJk-gFKc.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Pennies" -metadata track="2/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Pennies.mp4"  
move "You Know What's BS - Pennies.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=mBBwKWSxoMI  
ffmpeg -i "You Know What’s BS! Shoelaces-mBBwKWSxoMI.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Shoelaces" -metadata track="3/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Shoelaces.mp4"  
move "You Know What's BS - Shoelaces.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=mMoCgVDbWO0  
ffmpeg -i "You Know What’s BS! Penguin Movies-mMoCgVDbWO0.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Penguin Movies" -metadata track="4/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Penguin Movies.mp4"  
move "You Know What's BS - Penguin Movies.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=TSRBgfVBnjA  
ffmpeg -i "You Know What’s BS! Post Office Pens-TSRBgfVBnjA.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Post Office Pens" -metadata track="5/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Post Office Pens.mp4"  
move "You Know What's BS - Post Office Pens.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=oeyDkulK6lA  
ffmpeg -i "You Know What’s BS! Pay Toilets-oeyDkulK6lA.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Pay Toilets" -metadata track="6/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Pay Toilets.mp4"  
move "You Know What's BS - Pay Toilets.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=wi1GWXvzhxQ  
ffmpeg -i "You Know What’s BS! Temperature-wi1GWXvzhxQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Temperature" -metadata track="7/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Temperature.mp4"  
move "You Know What's BS - Temperature.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=bV0M9_NwMHY  
ffmpeg -i "You Know What’s BS! Printers-bV0M9_NwMHY.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Printers" -metadata track="8/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Printers.mp4"  
move "You Know What's BS - Printers.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=LYb3o8irBQM  
ffmpeg -i "You Know What’s BS! Christmas Aftermath-LYb3o8irBQM.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Christmas Aftermath" -metadata track="9/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Christmas Aftermath.mp4"  
move "You Know What's BS - Christmas Aftermath.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=hdowZnCV-tc  
ffmpeg -i "You Know What’s BS! Hotel TV's-hdowZnCV-tc.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Hotel TV's" -metadata track="10/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Hotel TV's.mp4"  
move "You Know What's BS - Hotel TV's.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=VsdzaEVeFEE  
ffmpeg -i "You Know What’s BS! DVDs-VsdzaEVeFEE.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="DVDs" -metadata track="11/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - DVDs.mp4"  
move "You Know What's BS - DVDs.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=nzLh9SqmqCA  
ffmpeg -i "You Know What’s BS! Movie Titles-nzLh9SqmqCA.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Movie Titles" -metadata track="12/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Movie Titles.mp4"  
move "You Know What's BS - Movie Titles.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=hG2otLyvuCQ  
ffmpeg -i "You Know What’s BS! Too Much Cream Cheese-hG2otLyvuCQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Too Much Cream Cheese" -metadata track="13/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Too Much Cream Cheese.mp4"  
move "You Know What's BS - Too Much Cream Cheese.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=bu3mcIfkUG8  
ffmpeg -i "You Know What’s BS! Fiber Envelopes & Packing Peanuts-bu3mcIfkUG8.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Video File Name: You Know What's BS! Fiber Envelopes & Packing Peanuts-bu3mcIfkUG8.webm" -metadata track="14/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Fiber Envelopes and Packing Peanuts.mp4"  
move "You Know What's BS - Fiber Envelopes and Packing Peanuts.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 243+251 https://www.youtube.com/watch?v=uGL2PvHvgWw  
ffmpeg -i "You Know What’s BS! DVD & Blu-ray Cases-uGL2PvHvgWw.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="DVD and Blu-Ray Cases" -metadata track="15/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - DVD and Blu-Ray Cases.mp4"  
move "You Know What's BS - DVD and Blu-Ray Cases.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=6Qnnxx-uHG4  
ffmpeg -i "You Know What’s BS! Traffic Spikes-6Qnnxx-uHG4.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Traffic Spikes" -metadata track="16/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Traffic Spikes.mp4"  
move "You Know What's BS - Traffic Spikes.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=V4ZqfvgUOWU  
ffmpeg -i "You Know What’s BS! iTunes-V4ZqfvgUOWU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="iTunes" -metadata track="17/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - iTunes.mp4"  
move "You Know What's BS - iTunes.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=a_nZJNxf0QE  
ffmpeg -i "You Know What’s BS! Feeding Birds-a_nZJNxf0QE.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Feeding Birds" -metadata track="18/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Feeding Birds.mp4"  
move "You Know What's BS - Feeding Birds.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=mJPXWQDxO8Q  
ffmpeg -i "You Know What’s BS! Wire Hangers-mJPXWQDxO8Q.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Wire Hangers" -metadata track="19/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Wire Hangers.mp4"  
move "You Know What's BS - Wire Hangers.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=9a4L-N__lJg  
ffmpeg -i "You Know What’s BS! Microwaves-9a4L-N__lJg.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Microwaves" -metadata track="20/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Microwaves.mp4"  
move "You Know What's BS - Microwaves.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=v1HQJIOByQU  
ffmpeg -i "You Know What’s BS! Assholes-v1HQJIOByQU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Assholes" -metadata track="21/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Assholes.mp4"  
move "You Know What's BS - Assholes.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=Httd7YE4sAs  
ffmpeg -i "You Know What’s BS! Car GPS-Httd7YE4sAs.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Car GPS" -metadata track="22/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Car GPS.mp4"  
move "You Know What's BS - Car GPS.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=UVZhVxSbaEs  
ffmpeg -i "You Know What’s BS! Warranties-UVZhVxSbaEs.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Warranties" -metadata track="23/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Warranties.mp4"  
move "You Know What's BS - Warranties.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=F18-BFmtVbM  
ffmpeg -i "You Know What’s BS! Amps That Don't Go to 11-F18-BFmtVbM.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Amps That Don't Go to 11" -metadata track="24/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Amps That Don't Go to 11.mp4"  
move "You Know What's BS - Amps That Don't Go to 11.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=9dEpLNj0QcE  
ffmpeg -i "You Know What’s BS! Grass-9dEpLNj0QcE.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Grass" -metadata track="25/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Grass.mp4"  
move "You Know What's BS - Grass.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=eHEItvqF-tg  
ffmpeg -i "You Know What’s BS! Vampires-eHEItvqF-tg.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Vampires" -metadata track="26/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Vampires.mp4"  
move "You Know What's BS - Vampires.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=mTcK4kynVLY  
ffmpeg -i "You Know What’s BS! Hotel Rooms-mTcK4kynVLY.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Hotel Rooms" -metadata track="27/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Hotel Rooms.mp4"  
move "You Know What's BS - Hotel Rooms.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=tBUzngDUOnk  
ffmpeg -i "You Know What’s BS! Word Pronunciations-tBUzngDUOnk.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Word Pronunciations" -metadata track="28/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Word Pronunciations.mp4"  
move "You Know What's BS - Word Pronunciations.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=C4Doj1AZInI  
ffmpeg -i "You Know What’s BS! Public Bathrooms-C4Doj1AZInI.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Public Bathrooms" -metadata track="29/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Public Bathrooms.mp4"  
move "You Know What's BS - Public Bathrooms.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=5Ja4FkSUsAk  
ffmpeg -i "You Know What’s BS! Water-5Ja4FkSUsAk.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Water" -metadata track="30/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Water.mp4"  
move "You Know What's BS - Water.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=kRhBahmZNAs  
ffmpeg -i "You Know What’s BS! Sleep-kRhBahmZNAs.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Sleep" -metadata track="31/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Sleep.mp4"  
move "You Know What's BS - Sleep.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=eHV_5fEu3ug  
ffmpeg -i "You Know What’s BS! Dangerous Funeral Processions-eHV_5fEu3ug.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Dangerous Funeral Processions" -metadata track="32/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Dangerous Funeral Processions.mp4"  
move "You Know What's BS - Dangerous Funeral Processions.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=qGL3zr3xDHU  
ffmpeg -i "You Know What’s BS! Oversized Packaging-qGL3zr3xDHU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Oversized Packaging" -metadata track="33/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Oversized Packaging.mp4"  
move "You Know What's BS - Oversized Packaging.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=IuAp-4j6QKQ  
ffmpeg -i "You Know What’s BS! Clothing Tags-IuAp-4j6QKQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Clothing Tags" -metadata track="34/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Clothing Tags.mp4"  
move "You Know What's BS - Clothing Tags.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=VzdAJJ4JnVM  
ffmpeg -i "You Know What’s BS! Wobbly table-VzdAJJ4JnVM.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Wobbly Tables" -metadata track="35/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Wobbly Tables.mp4"  
move "You Know What's BS - Wobbly Tables.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=Guu-mDvysxY  
ffmpeg -i "You Know What’s BS! Snow-Guu-mDvysxY.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Snow" -metadata track="36/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Snow.mp4"  
move "You Know What's BS - Snow.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=txa5ia2w7-k  
ffmpeg -i "You Know What’s BS! The Word Bimonthly-txa5ia2w7-k.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="The Word Bimonthly" -metadata track="37/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - The Word Bimonthly.mp4"  
move "You Know What's BS - The Word Bimonthly.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=NE-PdPttw4A  
ffmpeg -i "You Know What’s BS! Apple’s Lack of Buttons-NE-PdPttw4A.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Apple's Lack of Buttons" -metadata track="38/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Apple's Lack of Buttons.mp4"  
move "You Know What's BS - Apple's Lack of Buttons.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=1U5o7wllBTk  
ffmpeg -i "You Know What’s BS! Rolls of Tape-1U5o7wllBTk.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Rolls of Tape" -metadata track="39/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Rolls of Tape.mp4"  
move "You Know What's BS - Rolls of Tape.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=CawIjpm6okY  
ffmpeg -i "You Know What’s BS! Pogs-CawIjpm6okY.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Pogs" -metadata track="40/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Pogs.mp4"  
move "You Know What's BS - Pogs.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=6tW5E4KKSzY  
ffmpeg -i "You Know What’s BS! Stickers on Fruit-6tW5E4KKSzY.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Stickers on Fruit" -metadata track="41/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Stickers on Fruit.mp4"  
move "You Know What's BS - Stickers on Fruit.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=leU0Tj6QKLQ  
ffmpeg -i "You Know What’s BS! Inflatable Decorations-leU0Tj6QKLQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Inflatable Decorations" -metadata track="42/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Inflatable Decorations.mp4"  
move "You Know What's BS - Inflatable Decorations.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=joCUuDPUZjQ  
ffmpeg -i "You Know What’s BS! Group Texts-joCUuDPUZjQ.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Group Texts" -metadata track="43/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Group Texts.mp4"  
move "You Know What's BS - Group Texts.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=Fj_4J7DazPg  
ffmpeg -i "You Know What’s BS! Loud Startup Sounds-Fj_4J7DazPg.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Loud Startup Sounds" -metadata track="44/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Loud Startup Sounds.mp4"  
move "You Know What's BS - Loud Startup Sounds.mp4" "You Know What's BS [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=vVmL2BsCqi0  
ffmpeg -i "You Know What’s BS! Bed Sheets-vVmL2BsCqi0.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="You Know What's BS!?" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Cinemassacre" -metadata title="Bed Sheets" -metadata track="45/45" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "You Know What's BS - Bed Sheets.mp4"  
move "You Know What's BS - Bed Sheets.mp4" "You Know What's BS [Converted]" 

pause 
