mkdir "BodyBuilders [Converted]" 

youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=pqPi8WsOr3Q  
ffmpeg -i "If Pok‚mon Took Place in the 1800s-pqPi8WsOr3Q.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="BodyBuilders" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="If Pokémon Took Place in the 1800s" -metadata track="1/4" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "BodyBuilders - If Pokemon Took Place in the 1800s.mp4"  
move "BodyBuilders - If Pokemon Took Place in the 1800s.mp4" "BodyBuilders [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=wnMGJIUPlwI  
ffmpeg -i "If Pok‚mon Evolved in the 1800s-wnMGJIUPlwI.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="BodyBuilders" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="If Pokémon Evolved in the 1800s" -metadata track="2/4" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "BodyBuilders - If Pokemon Evolved in the 1800s.mp4"  
move "BodyBuilders - If Pokemon Evolved in the 1800s.mp4" "BodyBuilders [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=amK8JIOVVgk  
ffmpeg -i "How Pokemon Medicine Would Have Been HORRIFYING In the 1800s-amK8JIOVVgk.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="BodyBuilders" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="How Pokémon Medicine Would Have Been HORRIFYING in the 1800s" -metadata track="3/4" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "BodyBuilders - How Pokemon Medicine Would Have Been HORRIFYING in the 1800s.mp4"  
move "BodyBuilders - How Pokemon Medicine Would Have Been HORRIFYING in the 1800s.mp4" "BodyBuilders [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=ijACJQ4m3Ys  
ffmpeg -i "If Team Rocket Stole Pokemon in the 1800s-ijACJQ4m3Ys.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="BodyBuilders" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="If Team Rocket Stole Pokémon in the 1800s" -metadata track="4/4" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "BodyBuilders - If Team Rocket Stole Pokemon in the 1800s.mp4"  
move "BodyBuilders - If Team Rocket Stole Pokemon in the 1800s.mp4" "BodyBuilders [Converted]" 

pause 
