mkdir "Pokemon Ralphie [Converted]" 

youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=HUqP5xnwstc  
ffmpeg -i "Pokemon Ralphie - The Journey Begins-HUqP5xnwstc.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Pokémon Ralphie" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="The Journey Begins" -metadata track="1/9" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Pokemon Ralphie - The Journey Begins.mp4"  
move "Pokemon Ralphie - The Journey Begins.mp4" "Pokemon Ralphie [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=QKMoNz8uhRs  
ffmpeg -i "Pokemon Ralphie - Red Son-QKMoNz8uhRs.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Pokémon Ralphie" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="Red Son" -metadata track="2/9" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Pokemon Ralphie - Red Son.mp4"  
move "Pokemon Ralphie - Red Son.mp4" "Pokemon Ralphie [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=vUVYmBQs7RU  
ffmpeg -i "Pokemon Ralphie - FireGED Edition-vUVYmBQs7RU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Pokémon Ralphie" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="FireGED Edition" -metadata track="3/9" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Pokemon Ralphie - FireGED Edition.mp4"  
move "Pokemon Ralphie - FireGED Edition.mp4" "Pokemon Ralphie [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=BQBCH60PxSE  
ffmpeg -i "Pokemon Ralphie - Detective Squirtle on the Case-BQBCH60PxSE.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Pokémon Ralphie" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="Detective Squirtle on the Case" -metadata track="4/9" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Pokemon Ralphie - Detective Squirtle on the Case.mp4"  
move "Pokemon Ralphie - Detective Squirtle on the Case.mp4" "Pokemon Ralphie [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=GweAlYhUTbU  
ffmpeg -i "Pokemon Ralphie - Bill's FU-GweAlYhUTbU.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Pokémon Ralphie" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="Bill's FU" -metadata track="5/9" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Pokemon Ralphie - Bill's FU.mp4"  
move "Pokemon Ralphie - Bill's FU.mp4" "Pokemon Ralphie [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=UFYtCwEL4lA  
ffmpeg -i "Pokemon Ralphie VERSUS Detective Squirtle-UFYtCwEL4lA.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Pokémon Ralphie" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="Pokemon Ralphie VS. Detective Squirtle" -metadata track="6/9" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Pokemon Ralphie - Pokemon Ralphie VS. Detective Squirtle.mp4"  
move "Pokemon Ralphie - Pokemon Ralphie VS. Detective Squirtle.mp4" "Pokemon Ralphie [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=nUeldqWfi3I  
ffmpeg -i "Pokemon Ralphie Goes Alolan!-nUeldqWfi3I.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Pokémon Ralphie" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="Pokemon Ralphie Goes Alolan!" -metadata track="7/9" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Pokemon Ralphie - Pokemon Ralphie Goes Alolan.mp4"  
move "Pokemon Ralphie - Pokemon Ralphie Goes Alolan.mp4" "Pokemon Ralphie [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=RdZnHEf_qYk  
ffmpeg -i "Pokemon Ralphie - The Most Monstrous Pokemon Evolution!-RdZnHEf_qYk.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Pokémon Ralphie" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="The Most Monstrous Pokemon Evolution!" -metadata track="8/9" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Pokemon Ralphie - The Most Monstrous Pokemon Evolution.mp4"  
move "Pokemon Ralphie - The Most Monstrous Pokemon Evolution.mp4" "Pokemon Ralphie [Converted]" 
youtube-dl --embed-subs -f 244+251 https://www.youtube.com/watch?v=BOjKNWUT6OI  
ffmpeg -i "Pokemon Ralphie - THE FINALE!-BOjKNWUT6OI.webm" -map_metadata -1 -map_chapters -1 -map 0:0 -map 0:1 -id3v2_version 3 -metadata show="Pokémon Ralphie" -metadata media_type="tv" -metadata season_number="" -metadata episode_id="" -metadata artist="Dorkly" -metadata title="THE FINALE!" -metadata track="9/9" -metadata genre="Comedy" -metadata language="English" -threads 2 -c:a aac -profile:a aac_main -ac 2 -c:v libx264 -ar 44100 -b:a 160k -preset medium -profile:v main -level 3.0 -crf 20 -maxrate 8000k -bufsize 8000k -movflags +faststart "Pokemon Ralphie - THE FINALE.mp4"  
move "Pokemon Ralphie - THE FINALE.mp4" "Pokemon Ralphie [Converted]" 

pause 
